org: saraserverless
service: scraper-amazon-bestsellers

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [BestSellersTable, Arn]  # ARN da sua tabela DynamoDB
  httpApi:
    cors: true

functions:
  scrape:
    handler: scraper.scrape  # Verifique se está correto
    events:
      - httpApi:
          path: /scrape
          method: get
    timeout: 300  # Aumentado para garantir tempo suficiente para o scraper
    memorySize: 1024

plugins:
  - serverless-offline  # Você pode manter isso para desenvolvimento local

resources:
  Resources:
    BestSellersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ProductsTable
        AttributeDefinitions:
          - AttributeName: ProductID
            AttributeType: S  # Definindo como string
        KeySchema:
          - AttributeName: ProductID
            KeyType: HASH  # Definindo ProductID como chave primária
        BillingMode: PAY_PER_REQUEST
