org: saraserverless
service: scraper-amazon-bestsellers

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: dev
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt:
                - ProductsTable
                - Arn  # ARN da sua tabela DynamoDB
  httpApi:
    cors: true  # Permitir CORS para desenvolvimento local ou em produção
    shouldStartNameWithService: true  # Garante que o nome da API seja correto
    name: ${self:service}-${opt:stage, 'dev'}  # Define o nome da API para o serviço e o stage

functions:
  scrape:
    handler: scraper.scrapeAmazon
    events:
      - httpApi:
          path: /scrape
          method: get
    timeout: 30
    memorySize: 1024

  getProducts:
    handler: handler.getProductsHandler
    events:
      - httpApi:
          path: /products
          method: get
    timeout: 30
    memorySize: 1024

plugins:
  - serverless-offline  # Permitir rodar a API localmente para testes
  
resources:
  Resources:
    ProductsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ProductsTable
        AttributeDefinitions:
          - AttributeName: ProductID
            AttributeType: S  # Definir o tipo do atributo como String
        KeySchema:
          - AttributeName: ProductID
            KeyType: HASH  # A chave primária é o ProductID
        BillingMode: PAY_PER_REQUEST  # Pagamento por demanda (sem capacidade provisionada)
