org: saraserverless
service: scraper-amazon-bestsellers

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [BestSellersTable, Arn]  # ARN da sua tabela DynamoDB
  httpApi:
    cors: true

functions:
  scrape:
    handler: scraper.scrape
    layers:
      - "arn:aws:dynamodb:us-east-1:008971670952:table/ProductsTable"
    events:
      - httpApi:
          path: /scrape
          method: get
    timeout: 30
    memorySize: 1024

plugins:
  - serverless-offline


resources:
  Resources:
    BestSellersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: bestsellers_products  # Nome da tabela alterado para refletir o nome correto
        AttributeDefinitions:
          - AttributeName: title
            AttributeType: S
        KeySchema:
          - AttributeName: title  # Usar "title" como chave primária (ou adapte conforme necessário)
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
